---

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest
  tags:
    - docker
 
- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest
  tags:
    - docker

- name: Install lvm2
  yum:
    name: lvm2
    state: latest
  tags:
    - docker

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  tags:
    - docker

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  tags:
    - docker

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker

- name: Add user amoroz to docker group
  user:
    name: amoroz
    groups: docker
    append: yes
  tags:
    - docker

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 'u+x,g+x,o+x'
  tags:
    - docker